### ISSUE TITLE
tr.iter1.log里面的TokenAcc = 0%一直为零

### ISSUE THREAD

**Issue by Avatar4689** [Sundy1219/eesen-for-thchs30#10]
![1](https://user-images.githubusercontent.com/44045677/46777754-3c1f7e80-cd43-11e8-8fb1-d87fee25b019.PNG)

请问这是正常的吗？如果不是，可能是哪些方面的问题？谢谢解答！

**Comment by Avatar4689** [comment]
如果我接着训练，之后的tr.iter.log也会有大量的TokenAcc = 0%

**Comment by Sundy1219** [comment]
你这还才刚开始吧，等于0，正常，多训练几个epoch,再看结果吧＠Avatar4689

**Comment by Sundy1219** [comment]
你这才刚开始训练吧，等于0，正常，再跑几个epoch，看看＠Avatar4689

**Comment by Avatar4689** [comment]
> 你这还才刚开始吧，等于0，正常，多训练几个epoch,再看结果吧＠Avatar4689

感谢回复，我把exp删了重训就正常了

现在希望训timit的CTC，在训练这一步报错Dim() == v.Dim()，根据https://github.com/srvk/eesen/issues/208可能是特征维度的问题，但我提取特征和训练是直接用的你的代码，不会有问题才对。请问你之前有没有遇到过一样的问题？
