### ISSUE TITLE
你好 在训练的时候出现以下问题。

### ISSUE THREAD

**Issue by iezhanqingran** [Sundy1219/eesen-for-thchs30#11]
LOG (copy-feats:main():copy-feats.cc:100) Copied 10000 feature matrices.
copy-feats 'ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:data/dev/utt2spk scp:data/dev/cmvn.scp scp:exp/model_l4_c320/cv.scp ark:- |' ark,scp:exp/model_l4_c320/PkXAY/cv.ark,exp/model_l4_c320/cv_local.scp 
apply-cmvn --norm-vars=true --utt2spk=ark:data/dev/utt2spk scp:data/dev/cmvn.scp scp:exp/model_l4_c320/cv.scp ark:- 
LOG (apply-cmvn:main():apply-cmvn.cc:129) Applied cepstral mean and variance normalization to 893 utterances, errors on 0
LOG (copy-feats:main():copy-feats.cc:100) Copied 893 feature matrices.
TRAINING STARTS [2018-Nov-26 17:19:20]
[NOTE] TOKEN_ACCURACY refers to token accuracy, i.e., (1.0 - token_error_rate).
EPOCH 1 RUNNING ... Removing features tmpdir exp/model_l4_c320/PkXAY @ jurasix20
cv.ark	train.ark
请问是什么原因？
感谢。

**Comment by iezhanqingran** [comment]
@fantasyoooo
看见您也有这样的问题 能帮忙解决一下吗 多谢

**Comment by iezhanqingran** [comment]
检查了一下 是cuda的问题 但是我用的是集群并已指定了cuda_cmd

**Comment by iezhanqingran** [comment]
已解决

**Comment by wgfi110** [comment]
> 已解决

请问如何解决的，我也碰见了这个问题

**Comment by iezhanqingran** [comment]
> > 已解决
> 
> 请问如何解决的，我也碰见了这个问题

检查下log里的iter.00.log
