### ISSUE TITLE
资料准备阶段读不了文件，不知道是什么一回事

### ISSUE THREAD

**Issue by fantasyoooo** [Sundy1219/eesen-for-thchs30#2]
root@amax:/data/kaldi-master/eesen-for-thchs30# ./run.sh
=====================================================================
                       TLG WFST Construction                       
=====================================================================
========================================
            Data Preparation    
========================================
creating data/{train,dev,test}
cleaning data/train
preparing scps and text in data/train
.
.
.
sed: can't read /data/kaldi-master/eesen-for-thchs30/corpus/data/A14_42.wav.trn: No such file or directory
sed: can't read /data/kaldi-master/eesen-for-thchs30/corpus/data/A14_43.wav.trn: No such file or directory
sed: can't read /data/kaldi-master/eesen-for-thchs30/corpus/data/A14_44.wav.trn: No such file or directory

**Comment by Sundy1219** [comment]
/data/kaldi-master/eesen-for-thchs30/corpus/data/A14_44.wav.trn
这个目录一看就不对啊，你的home目录呢，你这是放在根目录下把@fantasyoooo
