### ISSUE TITLE
 求助：Generating Lexicon FST and CTC tokens FST 这一步出错了..怎么办

### ISSUE THREAD

**Issue by fantasyoooo** [Sundy1219/eesen-for-thchs30#3]
=============================================
 Generating Lexicon FST and CTC tokens FST 
=============================================
utils/ctc_compile_dict_token.sh: line 65: fstcompile: command not found
utils/ctc_compile_dict_token.sh: line 66: fstarcsort: command not found
Traceback (most recent call last):
  File "utils/ctc_token_fst.py", line 26, in <module>
    print str(nodeX) + ' ' + str(nodeX) + ' ' +  phone + ' <eps>';
IOError: [Errno 32] Broken pipe

**Comment by fantasyoooo** [comment]
应该是path.sh里面的环境变量没有设置好

**Comment by Sundy1219** [comment]
openfst 安装成功了没？安装好后，要把bin文件（比如fstcompile,fstarcsort)的目录加到~/.bashrc下
export PATH=$PATH:YOURS   @fantasyoooo

**Comment by fantasyoooo** [comment]
openfst在kaldi里面安装成功了，path.sh里面也加入了对kaldi里面的路径
export EESEN_ROOT=/data/kaldi
export PATH=$PWD/utils/:$EESEN_ROOT/src/nnetbin:$EESEN_ROOT/src/featbin:$EESEN_ROOT/src/decoder:$EESEN_ROOT/src/fstbin:$EESEN_ROOT/src/lmbin:$EESEN_ROOT/tools/openfst-1.6.2/bin:$EESEN_ROOT/tools/irstlm/bin/:$PWD:$PATH
export LC_ALL=C

**Comment by fantasyoooo** [comment]
现在卡着我的是model training这块：

Model Training这里出错了...
Traceback (most recent call last):
File "utils/prep_ctc_trans.py", line 75, in
out_line += dict[unk_word] + ' '
KeyError: ''
Traceback (most recent call last):
File "utils/prep_ctc_trans.py", line 75, in
out_line += dict[unk_word] + ' '
KeyError: ''

对应是train.sh里面的：

Label sequences; simply convert words into their label indices：
utils/prep_ctc_trans.py data/lang/lexicon_numbers.txt data/train/text "" | gzip -c - > $dir/labels.tr.gz

utils/prep_ctc_trans.py data/lang/lexicon_numbers.txt data/dev/text "" | gzip -c - > $dir/labels.cv.gz

看起来应该是和oov有关，请问这是怎么一回事..难道是我用的lexicon.txt和word.3gram.lm不对么..我是直接拿thchs30在openslr上面发布的词典和语言模型用的..

**Comment by Sundy1219** [comment]
![888](https://user-images.githubusercontent.com/19542945/30857408-2916fea6-a2ee-11e7-87bb-f207d356946e.png)
你的text里的词在lexicon_numbers.txt里找不到对应的id。这是我的lexicon_numbers.txt,你对照看看，和语言模型没关系@fantasyoooo

**Comment by Sundy1219** [comment]
![lexicon_numbers txt](https://user-images.githubusercontent.com/19542945/30857574-c6de84b0-a2ee-11e7-99f8-c9b5b3e1dc3c.png)

你的text里的词在lexicon_numbers.txt里找不到对应的id。这是我的lexicon_numbers.txt,你对照看看，和语言模型没关系@fantasyoooo

**Comment by fantasyoooo** [comment]
![2017-09-27 09 33 29](https://user-images.githubusercontent.com/31401967/30892080-42889b1c-a369-11e7-8b07-20f37796b047.png)
感谢你的回复，我发现我的lexicon_numbers.txt开头没有<UNK> 3 这一项，是不是就是导致这个问题的关键呢？
Traceback (most recent call last):
File "utils/prep_ctc_trans.py", line 75, in
out_line += dict[unk_word] + ' '
KeyError: ''

![2017-09-27 09 33 59](https://user-images.githubusercontent.com/31401967/30892284-555fd7ae-a36a-11e7-8637-3f0a2eb6fa42.png)
还有tokens.txt的开头也不一样...

问题究竟出现在哪里呢，是因为字典lexicon.txt的问题还是系统环境的问题..  @Sundy1219

**Comment by Sundy1219** [comment]
不会是系统的问题，是字典的问题，好好检查noise之类的label@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219 感谢回复，字典怎么检查..我是kaldi新手..用的是清华自己发布的资源里面的字典也会有错么..
![2017-09-27 11 17 04](https://user-images.githubusercontent.com/31401967/30894308-a18e373c-a375-11e7-8bd8-12162a052baa.png)

**Comment by Sundy1219** [comment]
![yy](https://user-images.githubusercontent.com/19542945/30894393-1c2f1f06-a376-11e7-8059-be51c2e1be76.png)
你train.sh中这一段的代码，和我的一样吗?

**Comment by Sundy1219** [comment]
如果一样，在你的lexicon.txt中加入一行内容
<UNK> UNK

**Comment by Sundy1219** [comment]
因为这段代码中又加入了一个 '<UNK>'这个标签，所以字典中也要有的@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219 
收到，感谢回复
代码是一样的，请问UNK是这样加么..？

![2017-09-27 11 30 14](https://user-images.githubusercontent.com/31401967/30894708-cea9164a-a377-11e7-97f4-f5370bdbf455.png)

**Comment by Sundy1219** [comment]
恩恩，是的，你再跑一下，应该不会有问题了

**Comment by fantasyoooo** [comment]
@Sundy1219 
十分感谢，目前问题是没有了，可是model training 这部分很奇怪，没显示错误但是感觉没开始训练模型..



![2017-09-27 12 38 16](https://user-images.githubusercontent.com/31401967/30896199-c7817a4c-a381-11e7-9d9f-f078e4f30938.png)

**Comment by Sundy1219** [comment]
确实没有在训练，真正训练时应该是下面这个样子
![training](https://user-images.githubusercontent.com/19542945/30896850-ab02158a-a385-11e7-8943-6faca72f7cf3.png)

把你的train_ctc_parallel.sh 里代码贴出来，我看下@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219 感谢回复  代码我是在github里面clone下来的..


![2017-09-27 15 08 50](https://user-images.githubusercontent.com/31401967/30900424-89aae220-a396-11e7-9ba9-7bd07f2dafd9.png)
![2017-09-27 15 09 12](https://user-images.githubusercontent.com/31401967/30900443-9907f3de-a396-11e7-933c-95046ec59a13.png)
![2017-09-27 15 09 48](https://user-images.githubusercontent.com/31401967/30900450-a4cd736a-a396-11e7-9788-1b3c9a61e74b.png)
![2017-09-27 15 10 17](https://user-images.githubusercontent.com/31401967/30900469-b31b98e8-a396-11e7-91b7-5713c2a1193e.png)
![2017-09-27 15 10 43](https://user-images.githubusercontent.com/31401967/30900476-b7c345f8-a396-11e7-9300-ff8752092f07.png)

**Comment by Sundy1219** [comment]
你在终端下输  train-ctc-parallel，看这个存不存在，可能是这个路径没加对，
export PATH=$PWD/utils/:$EESEN_ROOT/src/nnetbin    nnetbin 应该是netbin吧@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219 感谢回复，怎么判断路径是否加对了..
![2017-09-27 16 15 04](https://user-images.githubusercontent.com/31401967/30903138-4d2cd128-a3a0-11e7-99c6-fea27008612e.png)
![2017-09-27 16 15 47](https://user-images.githubusercontent.com/31401967/30903142-51c975ba-a3a0-11e7-9fbd-8e8cb705379c.png)
![2017-09-27 16 16 11](https://user-images.githubusercontent.com/31401967/30903189-7e5ed598-a3a0-11e7-8c5e-986cdc60448e.png)

export PATH=$PWD/utils/:$EESEN_ROOT/src/nnetbin  这个我是把路径指向kaldi里面的..kaldi的src文件夹里面的是nnetbin..
![2017-09-27 16 16 34](https://user-images.githubusercontent.com/31401967/30903237-a5e831a4-a3a0-11e7-8c22-9e9d1cb3da88.png)
![2017-09-27 16 17 03](https://user-images.githubusercontent.com/31401967/30903239-a908a01c-a3a0-11e7-9e92-e20290680f23.png)

**Comment by Sundy1219** [comment]
先去把eesen代码编译成功吧，https://github.com/srvk/eesen.git，里面有Install

**Comment by fantasyoooo** [comment]
@Sundy1219 感谢回复，对了 这个和文件的位置有关系么
在corpus文件夹的dev、test、train里面的.wav.trn是个链接指向corpus的data文件夹里面，这是原本thchs30的数据就是这样的了..
![2017-09-27 16 28 00](https://user-images.githubusercontent.com/31401967/30903513-9a929280-a3a1-11e7-917f-1759730b5a7d.png)
![2017-09-27 16 29 26](https://user-images.githubusercontent.com/31401967/30903527-a9fde6ac-a3a1-11e7-8dbc-c996c2aa7bf3.png)
![2017-09-27 16 29 46](https://user-images.githubusercontent.com/31401967/30903565-cf44b88c-a3a1-11e7-81d4-ce7354fa6a36.png)
![2017-09-27 16 30 32](https://user-images.githubusercontent.com/31401967/30903576-dc84a958-a3a1-11e7-8d0f-6d93b1d14adc.png)

**Comment by Sundy1219** [comment]
和数据没关系，数据没问题。你是eesen代码没编译，去编译成功，就可以了

**Comment by fantasyoooo** [comment]
@Sundy1219  收到，感谢

**Comment by fantasyoooo** [comment]
@Sundy1219 
你好..
eesen的编译卡在了ATLAS的安装上..显示的错误是cpu throttling enabled，我的cpu有32个..
![2017-09-28 16 25 17](https://user-images.githubusercontent.com/31401967/30956444-f06efb12-a469-11e7-94c1-603decfa2e6a.png)

**Comment by fantasyoooo** [comment]
@Sundy1219 
对了..eesen的tools里面安装的是srilm
![2017-09-28 17 34 10](https://user-images.githubusercontent.com/31401967/30959789-c6cc6e3e-a473-11e7-9c96-35ba109ed828.png)
而您path.sh里面写的是irstlm..
![2017-09-28 17 34 00](https://user-images.githubusercontent.com/31401967/30959867-02fb9808-a474-11e7-818a-fc09102d493a.png)
我要不要在eesen的tools里面不安装srilm，改成安装irstlm，或者两个都安装..

**Comment by Sundy1219** [comment]
安装srilm成功后指定路径就可以了，不用装irstlm。ATLAS，找个库安装。还有要GPU安装啊，不然训练贼慢啊@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219    感谢回复
前天晚上开始跑了..不过跑的特别慢，大概10小时一个epoch，应该是没用到gpu，可是服务器本身就已经安装了cuda..是不是在src编译的时候没有用到cuda么，我国庆后回去再试试重新编译

**Comment by Sundy1219** [comment]
INSTALL 文件里这个是cuda配置./configure --shared --cudatk-dir=/path/to/cuda_library
加上这个重新编译吧

**Comment by fantasyoooo** [comment]
@Sundy1219 
你好...cuda是安装了的，之前跑过kaldi的例子，也用了
root@amax:/data/eesen/src# ./configure --shared --cudatk-dir=/path/to/cuda_library
这个命令，但是cuda就是没配置进去eesen..
![2017-10-10 10 18 30](https://user-images.githubusercontent.com/31401967/31366593-71bcaff0-ada4-11e7-8285-3255d8e7718f.png)

**Comment by Sundy1219** [comment]
./configure --shared --cudatk-dir=/usr/local/cuda
一般是这样子的配置@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219 
感谢回复..
汇报一下：过程一波三折..终于train部分跑成功了，但decode又出现了问题0.0
![2017-10-17 18 58 53](https://user-images.githubusercontent.com/31401967/31661474-6e3cd03e-b36d-11e7-9150-0a0a1e94f972.png)
log记录从第19行有个failed..
![2017-10-17 18 56 16](https://user-images.githubusercontent.com/31401967/31661530-a7a71898-b36d-11e7-9b12-308a2174ab27.png)
很是头疼..

**Comment by fantasyoooo** [comment]
@Sundy1219 
还有lat.*.gz里面无内容..
![2017-10-17 19 12 02](https://user-images.githubusercontent.com/31401967/31661951-2a71e5ea-b36f-11e7-819a-cdaebe0affe1.png)

**Comment by fantasyoooo** [comment]
@Sundy1219 
这是我的lexicon.txt..
![2017-10-17 19 29 48](https://user-images.githubusercontent.com/31401967/31662619-bf5b0b1c-b371-11e7-8fc1-86f87a26c9cb.png)
lexicon_numbers.txt..
![2017-10-17 19 30 04](https://user-images.githubusercontent.com/31401967/31662649-e09da140-b371-11e7-9677-00a4cb206395.png)
tokens.txt..
![2017-10-17 19 30 33](https://user-images.githubusercontent.com/31401967/31662671-f436f06c-b371-11e7-8341-79ad08f76ea1.png)
0.0..

**Comment by fantasyoooo** [comment]
@Sundy1219 
我知道错误的地方了..
重新跑一次..
![2017-10-18 13 14 34](https://user-images.githubusercontent.com/31401967/31701954-60266cdc-b406-11e7-864a-d186d39b9178.png)

**Comment by Sundy1219** [comment]
语言模型格式不对吧，检查一下吧@fantasyoooo

**Comment by fantasyoooo** [comment]
@Sundy1219 
好滴好滴..

**Comment by fantasyoooo** [comment]
@Sundy1219 
感谢回复..
貌似跑完了，可是感觉有点奇怪..
![2017-10-19 18 13 24](https://user-images.githubusercontent.com/31401967/31766652-bf2cc2ea-b4fa-11e7-96c6-913c7858eb88.png)
decode.*.log里面有解码出来的句子..
![2017-10-19 18 23 18](https://user-images.githubusercontent.com/31401967/31766730-0a25c9ae-b4fb-11e7-8d8c-c9720164832c.png)
但是我在exp里面没有看到WER..decode_ctc_lat.sh里面是有scoring的..是我的程序还没有完全跑完么
![2017-10-19 18 23 42](https://user-images.githubusercontent.com/31401967/31767004-2356631a-b4fc-11e7-9c8e-2d61f5cbac5c.png)

**Comment by fantasyoooo** [comment]
@Sundy1219 
重新跑了两次decode..cer_*和wer_* 都是从5开始..
![2017-10-21 09 36 52](https://user-images.githubusercontent.com/31401967/31846852-c5fa96c0-b643-11e7-8a17-209fbc5688ba.png)
cer_*里面的WER都是大于35..不是说最终的解码WER:25%左右么，那问题出现在哪里呢..
![2017-10-21 09 42 56](https://user-images.githubusercontent.com/31401967/31846881-3cff6f7a-b644-11e7-8288-b2c1411d6f33.png)
