### ISSUE TITLE
运行local/thchs-30_decode_graph.sh时出错

### ISSUE THREAD

**Issue by zhiweizhong** [Sundy1219/eesen-for-thchs30#6]
你好，在运行local/thchs-30_decode_graph.sh data/language_model data/lang data/search_Graph命令时，报错如下：

```
=====================================================================
                       TLG WFST Construction
=====================================================================
==============================================================
   Generating The Language Model FST And Composing TLG.fst
==============================================================
fstcompile: /home/zhongzhiwei/speech_recognition/eesen_master/tools/openfst-1.4.1/bin/fstcompile
arpa2fst -
Processing 1-grams
Processing 2-grams
Processing 3-grams
Connected 0 states without outgoing arcs.
FATAL: FstCompiler: Symbol "a1" is not mapped to any integer arc ilabel, symbol table = data/search_Graph/words.txt, source = standard input, line = 3
ERROR: FstHeader::Read: Bad FST header: standard input
ERROR: FstHeader::Read: Bad FST header: standard input
```

不知道这个是什么原因？

另外，我发现我生成的lexicon_numbers.txt跟你不太一样，我的lexicon_numbers.txt是这样：

![image](https://user-images.githubusercontent.com/5139074/39626634-5abfde0c-4fd5-11e8-8d7c-c680ff315a2e.png)

还有，我想请问下，你使用的字典lexicon.txt，是thchs-30中的resource\dict\lexicon.txt的吗？

**Comment by Sundy1219** [comment]
![2018-05-08 09-45-58](https://user-images.githubusercontent.com/19542945/39733319-c6f19b52-52a4-11e8-9dbc-2a906b789ac8.png)
符号“a1”，是什么鬼？查看lexicon.txt，lexicon_numbers.txt以及data/search_Graph/words.txt,中的词是不是一致？

**Comment by Sundy1219** [comment]
你的lexicon.txt，是句子分词后，按照units.txt中的声韵母来生成的，你的语言模型中出现的词，不能在词典范围之外＠zhiweizhong
